### ISSUE TITLE
Not correct boundingCoordinates

### ISSUE THREAD

**Issue by RUjmiak** [anthonymartin/GeoLocation.php#6]
Hello,

I am trying to create boundingCoordinates from 48.1502228 17.0621223 with distance for example 10km.

Result are next coordinates
48.0602907806  16.9273279672 
48.2401548194  17.1969166328

From both points distance is more than 10km (more than 13km). 

What causes such a deviation?

Thanks

**Comment by NielsdeBlaauw** [comment]
Hi @RUjmiak,

I made the following image to explain why this occurs.

![explanation-size](https://cloud.githubusercontent.com/assets/661876/9758887/a50f4e3a-56e9-11e5-9f1d-e8f314f1fd95.png)

**Comment by n-sviridenko** [comment]
this point:

```45.7640299
4.8350211```

returns this bounds (for 10 kilometers):

```45.853961919433
4.9639346888526```

```45.674097880567
4.7061075111474```

This bounds have a rectangle 10x7 (lat x lng), instead of 10x10. Why?

**Comment by anthonymartin** [comment]
Thanks for bringing this up.

Someone will have to look at the reference code found [here](http://janmatuschek.de/LatitudeLongitudeBoundingCoordinates) to see if there are issues in this PHP implementation.

It might be a good idea to run some tests in the different languages published in the above link, and see if the tests run with the same results in this PHP implementation.

**Comment by hassansw** [comment]
The thing is i want to generate a fence on a specific location and want to match 
if ( inputLocation -> isWithinTheFence) is true/false
