### ISSUE TITLE
Require script in composer.json

### ISSUE THREAD

**Issue by farhood90** [anthonymartin/GeoLocation.php#7]
Hi, 

this must be a very idiotic question to you but I'm a noob.
What is the code for the composer.json. I mean the "require" code. I tried many things but doesnt seem to work for me.
Thank you.

**Comment by pfuhrmann** [comment]
This is packagist page:
https://packagist.org/packages/anthonymartin/geo-location

I would suggest:
"anthonymartin/geo-location": "~1.0"

**Comment by farhood90** [comment]
Thanks a lot for your help. great website.
"anthonymartin/geo-location": "dev-master" worked for me. I had tried it before but didnt work. I might have had a typo or a glitch somewhere else.
