### ISSUE TITLE
Need To Know

### ISSUE THREAD

**Issue by hassansw** [anthonymartin/GeoLocation.php#8]
The thing is i want to generate a fence on a specific location and want to match 
if ( inputLocation -> isWithinTheFence) is true/false

**Comment by Darunada** [comment]
This should help you, I didn't test it

```php
<?php

/**
 * Checks if the $location is within $distance from $center
 *
 */
function isWithinCircle(GeoLocation $location, GeoLocation $center, $distance, $unitOfMeasurement = 'km') {
		$range = $center->distanceTo($location, $unitOfMeasurement);
		return $range < $distance;
}

/**
 * Checks if the $location is inside a "square" with edge length 2*$distance centered at $center
 *
 */
function isWithinTheFence(GeoLocation $location, GeoLocation $center, $distance, $unitOfMeasurement = 'km') {
	$inRange = isWithinCircle($location, $center, $distance, $unitOfMeasurement);

	// need to check the bounds to make the region "square"
	if(!$inRange) {
		list($min, $max) = $center->boundingCoordinates($distance, $unitOfMeasurement);
		$inRange = $min->getLatitudeInDegrees() <= $location->getLatitudeInDegrees();
		$inRange = $inRange && $min->getLongitudeInDegrees() <= $location->getLongitudeInDegrees();
		$inRange = $inRange && $max->getLatitudeInDegrees() >= $location->getLatitudeInDegrees();
		$inRange = $inRange && $min->getLongitudeInDegrees() >= $location->getLongitudeInDegrees();
	}
	
	return $inRange;
}


$center = GeoLocation::fromDegrees($centerLat, $centerLon);
$myLocation = GeoLocation::fromDegrees($myLat, $myLon);
$inRange = isWithinTheFence($myLocation, $center, 15, 'km', true);
```

**Comment by hassansw** [comment]
Thanks mate will try it out :)

**Comment by hassansw** [comment]
@Darunada Im confused need help

**Comment by hassansw** [comment]
Works almost perfect

**Comment by hassansw** [comment]
function isWithinCircle(GeoLocation $location, GeoLocation $center, $distance, $unitOfMeasurement = 'km') {
        $range = $center->distanceTo($location, $unitOfMeasurement);
        return $range < $distance;
}
/**
 * Checks if the $location is inside a "square" with edge length 2*$distance centered at $center
 *
 */
function isWithinTheFence(GeoLocation $location, GeoLocation $center, $distance, $unitOfMeasurement = 'km') {
    $inRange = isWithinCircle($location, $center, $distance, $unitOfMeasurement);
		// if(isset($inRange)){echo "The value is set as:";}
		if($inRange == 1 ){echo "The location is within the fence...\n<br>";}
		else {
			echo "The location is not in the fence";
		}
    // need to check the bounds to make the region "square"
    if(!$inRange) {
        list($min, $max) = $center->boundingCoordinates($distance, $unitOfMeasurement);
        $inRange = $min -> getLatitudeInDegrees() <= $location->getLatitudeInDegrees();
        $inRange = $inRange && $min->getLongitudeInDegrees() <= $location->getLongitudeInDegrees();
        $inRange = $inRange && $max->getLatitudeInDegrees() >= $location->getLatitudeInDegrees();
        $inRange = $inRange && $min->getLongitudeInDegrees() >= $location->getLongitudeInDegrees();
    }
    return $inRange ;
}
$center = GeoLocation::fromDegrees(24.954072, 67.071324);
$myLocation = GeoLocation::fromDegrees(24.955112, 67.071418);
$inRange = isWithinTheFence($myLocation, $center, 1, 'km');

//Need to check the output of the $inRange Variable
